import { Component, Listen } from '@stencil/core';

@Component({
  tag: 'my-name',
  styleUrl: 'my-name.scss'
})
export class MyName {

  @Listen('clickElement')
  handleClick = (ev) => console.log(ev.detail);

  render() {
    const header = [{key: 'others_lost',value: 'Otros costes'},{key: 'students',value: 'Estudiantes'},{key: 'others',value: 'Otros'},{key: 'teachers_new',value: 'Nuevos profesores'},{key: 'month',value: 'Mes'},{key: 'students_new',value: 'Nuevos estudiantes'},{key: 'year',value: 'Año'},{key: 'tablets',value: 'Tablets'},{key: 'students_lost',value: 'Estudiantes perdidos'},{key: 'others_new',value: 'Otros nuevos'},{key: 'teachers_lost',value: 'Coste de profesores'},{key: 'teachers',value: 'Profesores'},{key: 'packs',value: 'Maletas'}];
    // const data = [
    //   {'H1': 'C1','H2': 'C2','H3': 'C3','H4': 'C4','H5': 'C5','H6': 'C6','H7': 'C7','H8': 'C8','H9': 'C9','H10': 'C10'},
    //   {'H1': 'C1','H2': 'C2','H3': 'C3','H4': 'C4','H5': 'C5','H6': 'C6','H7': 'C7','H8': 'C8','H9': 'C9','H10': 'C10'},
    //   {'H1': 'C1','H2': 'C2','H3': 'C3','H4': 'C4','H5': 'C5','H6': 'C6','H7': 'C7','H8': 'C8','H9': 'C9','H10': 'C10'}
    // ]
    const data = [
      
     {
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },{
        others_lost: '0',
        students: '311',
        others: '3',
        teachers_new: '0',
        month: 'Enero',
        students_new: '0',
        year: '0001',
        tablets: '0',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '14',
        packs: '1'
      },
      {
        others_lost: '0',
        students: '834',
        others: '9',
        teachers_new: '29',
        month: 'Febrero',
        students_new: '834',
        year: '2016',
        tablets: '75',
        students_lost: '0',
        others_new: '9',
        teachers_lost: '0',
        teachers: '29',
        packs: '3'
      },
      {
        others_lost: '0',
        students: '1255',
        others: '12',
        teachers_new: '18',
        month: 'Marzo',
        students_new: '421',
        year: '2016',
        tablets: '125',
        students_lost: '0',
        others_new: '3',
        teachers_lost: '0',
        teachers: '47',
        packs: '5'
      },
      {
        others_lost: '0',
        students: '1535',
        others: '15',
        teachers_new: '10',
        month: 'Abril',
        students_new: '280',
        year: '2016',
        tablets: '150',
        students_lost: '0',
        others_new: '3',
        teachers_lost: '0',
        teachers: '57',
        packs: '6'
      },
      {
        others_lost: '0',
        students: '1633',
        others: '21',
        teachers_new: '7',
        month: 'Mayo',
        students_new: '98',
        year: '2016',
        tablets: '175',
        students_lost: '0',
        others_new: '3',
        teachers_lost: '0',
        teachers: '64',
        packs: '7'
      },
      {
        others_lost: '0',
        students: '2818',
        others: '45',
        teachers_new: '61',
        month: 'Junio',
        students_new: '1185',
        year: '2016',
        tablets: '375',
        students_lost: '0',
        others_new: '24',
        teachers_lost: '0',
        teachers: '125',
        packs: '15'
      },
      {
        others_lost: '0',
        students: '2321',
        others: '48',
        teachers_new: '16',
        month: 'Julio',
        students_new: '569',
        year: '2016',
        tablets: '400',
        students_lost: '1066',
        others_new: '3',
        teachers_lost: '30',
        teachers: '111',
        packs: '16'
      },
      {
        others_lost: '0',
        students: '2652',
        others: '281',
        teachers_new: '68',
        month: 'Agosto',
        students_new: '2049',
        year: '2016',
        tablets: '475',
        students_lost: '1718',
        others_new: '233',
        teachers_lost: '53',
        teachers: '126',
        packs: '19'
      },
      {
        others_lost: '226',
        students: '3247',
        others: '57',
        teachers_new: '25',
        month: 'Septiembre',
        students_new: '595',
        year: '2016',
        tablets: '475',
        students_lost: '0',
        others_new: '2',
        teachers_lost: '0',
        teachers: '151',
        packs: '19'
      },
      {
        others_lost: '1',
        students: '3776',
        others: '60',
        teachers_new: '25',
        month: 'Octubre',
        students_new: '530',
        year: '2016',
        tablets: '475',
        students_lost: '1',
        others_new: '4',
        teachers_lost: '3',
        teachers: '173',
        packs: '19'
      },
      {
        others_lost: '0',
        students: '3791',
        others: '61',
        teachers_new: '0',
        month: 'Noviembre',
        students_new: '17',
        year: '2016',
        tablets: '475',
        students_lost: '2',
        others_new: '1',
        teachers_lost: '0',
        teachers: '173',
        packs: '19'
      },
      {
        others_lost: '0',
        students: '3791',
        others: '61',
        teachers_new: '0',
        month: 'Diciembre',
        students_new: '0',
        year: '2016',
        tablets: '475',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '173',
        packs: '19'
      },
      {
        others_lost: '0',
        students: '3997',
        others: '64',
        teachers_new: '2',
        month: 'Enero',
        students_new: '2',
        year: '2017',
        tablets: '475',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '180',
        packs: '20'
      },
      {
        others_lost: '0',
        students: '5133',
        others: '69',
        teachers_new: '26',
        month: 'Febrero',
        students_new: '1138',
        year: '2017',
        tablets: '475',
        students_lost: '2',
        others_new: '8',
        teachers_lost: '1',
        teachers: '205',
        packs: '20'
      },
      {
        others_lost: '2',
        students: '6680',
        others: '69',
        teachers_new: '45',
        month: 'Marzo',
        students_new: '1586',
        year: '2017',
        tablets: '475',
        students_lost: '39',
        others_new: '2',
        teachers_lost: '0',
        teachers: '250',
        packs: '20'
      },
      {
        others_lost: '0',
        students: '7095',
        others: '72',
        teachers_new: '14',
        month: 'Abril',
        students_new: '418',
        year: '2017',
        tablets: '475',
        students_lost: '3',
        others_new: '3',
        teachers_lost: '1',
        teachers: '263',
        packs: '20'
      },
      {
        others_lost: '0',
        students: '7096',
        others: '72',
        teachers_new: '1',
        month: 'Mayo',
        students_new: '1',
        year: '2017',
        tablets: '475',
        students_lost: '0',
        others_new: '0',
        teachers_lost: '0',
        teachers: '264',
        packs: '20'
      },
      {
        others_lost: '0',
        students: '7178',
        others: '73',
        teachers_new: '7',
        month: 'Junio',
        students_new: '82',
        year: '2017',
        tablets: '475',
        students_lost: '0',
        others_new: '1',
        teachers_lost: '5',
        teachers: '266',
        packs: '20'
      },
      {
        others_lost: '0',
        students: '7305',
        others: '74',
        teachers_new: '1',
        month: 'Julio',
        students_new: '129',
        year: '2017',
        tablets: '475',
        students_lost: '2',
        others_new: '1',
        teachers_lost: '3',
        teachers: '264',
        packs: '20'
      },
      {
        others_lost: '0',
        students: '7808',
        others: '83',
        teachers_new: '20',
        month: 'Agosto',
        students_new: '512',
        year: '2017',
        tablets: '475',
        students_lost: '9',
        others_new: '9',
        teachers_lost: '1',
        teachers: '283',
        packs: '23'
      },
      {
        others_lost: '0',
        students: '11125',
        others: '433',
        teachers_new: '223',
        month: 'Septiembre',
        students_new: '3791',
        year: '2017',
        tablets: '475',
        students_lost: '3',
        others_new: '353',
        teachers_lost: '0',
        teachers: '493',
        packs: '40'
      },
      {
        others_lost: '352',
        students: '10401',
        others: '404',
        teachers_new: '11',
        month: 'Octubre',
        students_new: '47',
        year: '2017',
        tablets: '475',
        students_lost: '7410',
        others_new: '1',
        teachers_lost: '360',
        teachers: '470',
        packs: '36'
      },
      {
        others_lost: '1177',
        students: '12526',
        others: '432',
        teachers_new: '14',
        month: 'Noviembre',
        students_new: '664',
        year: '2017',
        tablets: '475',
        students_lost: '597',
        others_new: '6',
        teachers_lost: '18',
        teachers: '523',
        packs: '44'
      }
    ]
    return (
        <stencil-sch-footable header={header} data={data}></stencil-sch-footable>
        // <my-list lista={lista}></my-list>
    );
  }
}
