/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  MyName as MyName
} from './components/my-name/my-name';

declare global {
  interface HTMLMyNameElement extends MyName, HTMLElement {
  }
  var HTMLMyNameElement: {
    prototype: HTMLMyNameElement;
    new (): HTMLMyNameElement;
  };
  interface HTMLElementTagNameMap {
    "my-name": HTMLMyNameElement;
  }
  interface ElementTagNameMap {
    "my-name": HTMLMyNameElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-name": JSXElements.MyNameAttributes;
    }
  }
  namespace JSXElements {
    export interface MyNameAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  StencilSchFootable as StencilSchFootable
} from './components/stencil-sch-footable/stencil-sch-footable';

declare global {
  interface HTMLStencilSchFootableElement extends StencilSchFootable, HTMLElement {
  }
  var HTMLStencilSchFootableElement: {
    prototype: HTMLStencilSchFootableElement;
    new (): HTMLStencilSchFootableElement;
  };
  interface HTMLElementTagNameMap {
    "stencil-sch-footable": HTMLStencilSchFootableElement;
  }
  interface ElementTagNameMap {
    "stencil-sch-footable": HTMLStencilSchFootableElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "stencil-sch-footable": JSXElements.StencilSchFootableAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilSchFootableAttributes extends HTMLAttributes {
      
        header?: {key: string, value: string}[],
        data?: any[],
        minWidthCol?: number
    }
  }
}

